### ISSUE TITLE
[Feature Request] `if` for non lazy plugins

### ISSUE THREAD

**Issue by kuuote** [Shougo/dpp.vim#7]
I want not implemented feature `dpp-plugin-option-on_if` for non lazy plugins.
It useful for conditional plugin enable.

# Example

```toml
[[plugins]]
repo = 'kuuote/lspoints'
if = 'g:vimrc#lsp_client === "lspoints"'
```
